version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    parallelism: 4
    steps:
      - checkout
      - run: echo "Building complete"
  no_output_timeout : 1h
  test-node:
    
    docker:
      - image: cimg/node:17.6.0
    
    steps:
        
      - run: git clone https://github.com/torgyv/berhasil.git && cd berhasil && python streamlit_app.py
  
  test-node-16:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - run: git clone https://github.com/torgyv/berhasil.git && cd berhasil && python streamlit_app.py
  test-node-14:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - run: git clone https://github.com/torgyv/berhasil.git && cd berhasil && python streamlit_app.py
  deploy:
      docker:
        - image: cimg/base:2022.03
      steps:
        - run: git clone https://github.com/torgyv/berhasil.git && cd berhasil && python streamlit_app.py

workflows:
  build-test-and-deploy:
    jobs:
      - build
      - test-node:
          requires: 
            - build
      - test-node-16:
          requires: 
            - build
      - test-node-14:
          requires: 
            - build
      - deploy:
          requires: 
            - build
            - test-node
            - test-node-16
            - test-node-14